# version: '3'
# services:
#   server:
#     build: ./my-server
#     ports:
#       - "8080:8080"
#   app:
#     build: ./my-app
#     ports:
#       - "3000:3000"

version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: my-server/Dockerfile
    ports:
      - "${HOST_SERVER_PORT}:${CONTAINER_SERVER_PORT}"
    environment:
      - CONFIG_PATH=/app/siteConfig.json

  app:
    build:
      context: .
      dockerfile: my-app/Dockerfile
    ports:
      - "${HOST_APP_PORT}:${CONTAINER_APP_PORT}"
    environment:
      - REACT_APP_CONFIG_PATH=/app/siteConfig.json